- src/com/felhr/usbserial/BLED112SerialDevice.java
- src/com/felhr/usbserial/CDCSerialDevice.java
- src/com/felhr/usbserial/CP2102SerialDevice.java
- src/com/felhr/usbserial/FTDISerialDevice.java
- src/com/felhr/usbserial/PL2303SerialDevice.java
- src/com/felhr/usbserial/UsbSerialDevice.java
- src/com/felhr/usbserial/XdcVcpSerialDevice.java
(I've only tested this FTDI 0x0403/0x6010 adapter: http://www.delock.de/produkte/G_61886/merkmale.html)
> Added support for multi-interface devices.

- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialInterface.java
Added a method to set Rts on and off
> Rts functionality added in CP2102 class

- usbserial/src/main/java/com/felhr/usbserial/BLED112SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/PL2303SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialInterface.java
- usbserial/src/main/java/com/felhr/usbserial/XdcVcpSerialDevice.java
Added RTS signaling to CP210x devices
> Junaid76 master

- usbserial/src/main/java/com/felhr/usbserial/BLED112SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/PL2303SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialInterface.java
- usbserial/src/main/java/com/felhr/usbserial/XdcVcpSerialDevice.java
RTS/CTS and DTR/DSR flow control added to CP210x driver
> FlowControl RTS/CTS DTR/DSR added to CP210X

- example/src/main/java/com/felhr/serialportexample/MainActivity.java
- example/src/main/java/com/felhr/serialportexample/UsbService.java
- usbserial/src/main/java/com/felhr/usbserial/BLED112SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/PL2303SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialInterface.java
- usbserial/src/main/java/com/felhr/usbserial/XdcVcpSerialDevice.java
Flow control (RTS/CTS and DTR/DSR) for the CP2102 and FTDI devices
> Flow control signals

- usbserial/src/main/java/com/felhr/usbserial/BLED112SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/PL2303SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialInterface.java
- usbserial/src/main/java/com/felhr/usbserial/XdcVcpSerialDevice.java
Synchronous versions of write and read operations
> Synchronous operations

- README.md
- example/src/main/java/com/felhr/serialportexample/MainActivity.java
- usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
> Ch340 newdriver

- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
Parity callbacks added to FTDI and CP210x devices
> Parity ftdi cp2102

- usbserial/src/main/java/com/felhr/deviceids/CP2130Ids.java
- usbserial/src/main/java/com/felhr/usbserial/CP2130SpiDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSpiDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSpiInterface.java
SPI interface support (CP2130 chipset)
> SPI support

- example/src/main/res/layout/activity_main.xml
Minor issue in the example module
> Added scroll vertically automatically in TextView

- README.md
This is in response to ref #142
> Add note to readme about known issue

- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
Allowing RTS and DTR turned on/off on CDC. #153
> Allowing RTS and DTR turned on/off on CDC

- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/PL2303SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialDevice.java
Added function isOpen to check if a serial port is open
> added check open port

- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
> Fixes for databits, parity and stopbits in CP2102

- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialDevice.java
- usbserial/src/test/java/com/felhr/usbserial/FTDISerialDeviceTest.java
Also using System.arrayCopy in loop instead of manual copying
> Reuse same instance of byte array when the destination array is empty

- usbserial/build.gradle
- usbserial/proguard-rules.pro
You probably want to publish an AAR-file for this to kick in for consumers of the library.
> Added proguard rules to the AAR-package

- usbserial/src/main/java/com/felhr/usbserial/BLED112SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/CP2102SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/PL2303SerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialInterface.java
- usbserial/src/main/java/com/felhr/usbserial/XdcVcpSerialDevice.java
The set break feature is supported on FTDI now.
> Add a setBreak interface to support the set break feature

- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
Custom baud rates for FTDI devices
> Ftdi custom baudrates

- integration/integration_sync.py
- integrationapp/src/main/java/com/felhr/integrationapp/MainActivity.java
- integrationapp/src/main/java/com/felhr/integrationapp/UsbSyncService.java
- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
I will still try to fix the newer method because supposed improvements
> Back to previous FTDI sync read method. Referenced in #241

- usbserial/src/main/java/com/felhr/usbserial/FTDISerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/SerialInputStream.java
- usbserial/src/main/java/com/felhr/usbserial/SerialOutputStream.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialDevice.java
- usbserial/src/main/java/com/felhr/usbserial/UsbSerialInterface.java
SerialOutputStream: public void write(byte b[], int off, int len)
SerialInputStream:  public int read(byte b[], int off, int len)
UsbSerialDevice: public int syncRead(byte[] buffer, int offset, int length, int timeout)
UsbSerialDevice: public int syncWrite(byte[] buffer, int offset, int length, int timeout)
> Added sync and streams read/write methods with offsets

- usbserial/src/main/java/com/felhr/usbserial/CDCSerialDevice.java
Find the proper control index to use for CDC devices with multiple devices classes present.  This fixes the problem which prevented the library from working with STM32 Nucleo boards, among others.  Note that this does not change the behavior for devices without a USB_CLASS_COMM interface.
This assumes that if index 0 works today, that is what will be returned by `findFirstControl()`.  And if none are returned, the default value of 0 is returned, which was the hard-coded value used before this change.
This has been tested on two CDC devices, one that has a single CDC interface and was working with this library, and another multi-class device (and STM32 Nucleo32 board) which did not work.  After this change, both devices work with this library.
This change is needed to address …
> Use proper control index on multi-class CDC devices
